### ISSUE TITLE
Framed routing not working

### ISSUE THREAD

**Issue by DiogoCruz40** [s5uishida/open5gs_5gc_ueransim_framed_routing_sample_config#1]
I added the address, the route, and the subscriber information as you suggested. As a result, I am unable to ping it using the ogstun interface, but I can ping the uesimtun0 IP, 10.45.0.2. I would be grateful if you could assist me.

![Screenshot from 2023-03-03 22-49-55](https://user-images.githubusercontent.com/43995498/222847555-043b52dc-196b-4f9a-b42f-6d2c3f283ae8.png)
![Screenshot from 2023-03-03 22-49-32](https://user-images.githubusercontent.com/43995498/222847562-556eb5e9-3cfa-4877-9639-4472fb048355.png)
![Screenshot from 2023-03-03 22-49-20](https://user-images.githubusercontent.com/43995498/222847567-9e3b9aac-370b-4482-bc49-a3a71c6ebf51.png)

**Comment by s5uishida** [comment]
Hi @DiogoCruz40 

Framed routing is available from 2023.01.26, so what is the version (and source-date) of your Open5GS?

Also, in the `tcpdump` log on UE, do you see any packets going to `192.168.20.100`?

**Comment by DiogoCruz40** [comment]
Hello @s5uishida 

I just updated to 2.6.0 and still not working. What are the network functions that are responsible for the framed routing to work?

No i don't.

**Comment by DiogoCruz40** [comment]
I forgot to eliminate the old UE and instantiate a new UE when i added the field **ipv4_framed_routing** to the db. Now it's working! Thanks!

**Comment by DiogoCruz40** [comment]
One more question: using the UPF function, I can ping the framed routing IPs of UEs, but I can't ping from one UE to another. Is there a solution?

**Comment by s5uishida** [comment]
Hi @DiogoCruz40 

The routing for this is outside the scope of 5G core.
Please set the routing according to your environment.

**Comment by DiogoCruz40** [comment]
I see the only way would be using IP Tables. Thank you, i'm closing this issue now.
