### ISSUE TITLE
Some usage scenarios related issues

### ISSUE THREAD

**Issue by myonlystarWang** [s5uishida/open5gs_5gc_ueransim_framed_routing_sample_config#2]
Hi,
   Thank you very much for this FRAME Routing config of `Open5gs`!
   I would like to ask whether this can solve the two issues below?
   [https://github.com/open5gs/open5gs/issues/1386](url)
   [https://github.com/open5gs/open5gs/issues/1826](url)

   The other thing I want to ask is:
   Can 192.168.20.100 be pinged 192.168.21.100 in your environment?(Interconnection across terminal subnets)
   Thanks in advance!

**Comment by s5uishida** [comment]
@myonlystarWang 

It's a routing setting and out of scope for 5G core.

First of all, in my scenario for this repository, ping is fine between UE0 and UE1, regardless of Framed routing.

**UE0 (10.45.0.2) <--(ping OK)--> UE1 (10.45.0.3)**
```
UE0# ping 10.45.0.3 -I 10.45.0.2
```
```
UE1# ping 10.45.0.2 -I 10.45.0.3
```
Then, ping is fine between Framed routes belonging to different UEs.

**UE0 (192.168.20.100) <--(ping OK)--> UE1 (192.168.21.100, 192.168.22.100)**
```
UE0# ping 192.168.21.100 -I 192.168.20.100
UE0# ping 192.168.22.100 -I 192.168.20.100
```
```
UE1# ping 192.168.20.100 -I 192.168.21.100
UE1# ping 192.168.20.100 -I 192.168.22.100
```
In that case, I added the following routings on UPF.
```
UPF# ip route add 192.168.20.0/24 dev ogstun
UPF# ip route add 192.168.21.0/24 dev ogstun
UPF# ip route add 192.168.22.0/24 dev ogstun
```
Also, please refer to this for the below discussion, too.
https://github.com/open5gs/open5gs/discussions/2154

**Comment by myonlystarWang** [comment]
@s5uishida Thank you very, very much for your detailed reply!
You helped me to confirm the terminals connectivity to each other and frame routing connectivity can work in Open5gs.
Finally, I want to confirm which version of open5gs you used when doing these tests? And what thie linux version is used?

**Comment by s5uishida** [comment]
@myonlystarWang 

v2.6.1(2023.03.10) and Ubuntu 22.04.

**Comment by myonlystarWang** [comment]
> @myonlystarWang
> 
> v2.6.1(2023.03.10) and Ubuntu 22.04.

Got it!Thanks!
I have tested what you show,it works fine!
This ticket is closing now!And it will serve as a reference to the other two issues 
[https://github.com/open5gs/open5gs/issues/1386](url)
[https://github.com/open5gs/open5gs/issues/1826](url)
Thanks again!
